--INSERT INTO BI_CIN VALUES(
--	'FINANCEIRO - META FATURAMENTO',
--	'SP_BID_META_FATURAMENTO',
--	'ANTONIO.NETO',
--	GETDATE(),
--	'ANTONIO.NETO',
--	GETDATE()
--)

SELECT * FROM BI_IND

--UPDATE BI_IND SET cor1 = 255, cor2 = 65535, cor3 = 32768 WHERE CODIND = 11