--INSERT NA TABELA BI_CIN
  --SELECT * FROM BI_CIN

INSERT BI_CIN (
		DESCRI,
		SPNAME,
		USUATU,
		DATATU,
		USUINC,
		DATINC
		) 
VALUES ( 'TERMINAL CUBATAO - VEICULOS AGUARDANDO ENTRADA',
		'SP_BID_CORPORATE_VEICULOS_AGUARDANDO_ENTRADA',
	   'ALEX.CRUZ',
	   getdate(),
	   'ALEX.CRUZ',
	   getdate()
	   )

-- CORES DOS INDICADORES DO DEPOT --SELECT * FROM BI_IND

--UPDATE BI_IND SET cor1 = 32768, cor2 = 65535, cor3 = 255 where CODIND = 74 //verde / amarelo / vermelho
--UPDATE BI_IND SET cor1 = 32768, cor2 = 65535, cor3 = 255 where CODIND = 59
