--SELECT * FROM BI_CIN WHERE ID_CIN = 47 --HOMO
--SELECT * FROM BI_IND WHERE CODIND = 44 --HOMO

--INSERT BI_CIN (DESCRI, SPNAME, USUATU, DATATU, USUINC, DATINC) 
--VALUES ('DEPOTCE CUBATAO - TEMPO DE ESPERA PATIO',
--		'SP_BID_DEPOT_TEMPO_ESPERA_PATIO',
--		'ANTONIO.SERAFIM',
--		getdate(),
--		'ANTONIO.SERAFIM',
--		getdate())
		
--UPDATE BI_IND
--SET cor1 = 32768, cor2 = 65535, cor3 = 255
--WHERE CODIND = 44

--ALTER TABLE BI_IND ADD COR1 VARCHAR(10) NULL, COR2 VARCHAR(10) NULL, COR3 VARCHAR(10) NULL;