SELECT
	CASE
		WHEN Y.CODCAM IS NULL THEN X.CODCAM
		ELSE Y.CODCAM
	END AS CODCAM,
	X.CODMOT,
	X.NOMMOT,
	X.EMPREG,
	X.CODMTV,
	X.DESCRI,
	X.DATREF,
	X.OBSERV,
	CASE
		WHEN Y.CODCAM IS NULL THEN 'X' ELSE 'Y'
	END AS ID
FROM(
	SELECT
		mot.CODMOT,
		mot.NOMMOT,
		mot.EMPREG,
		mtv.CODMTV,
		mtv.DESCRI,
		cam.CODCAM,
		cam.DATREF,
		cam.OBSERV
	FROM
		RODCAM cam LEFT JOIN RODMOT mot ON
			cam.CODMOT = mot.CODMOT
		LEFT JOIN RODMTV mtv ON
			cam.CODMTV = mtv.CODMTV
	WHERE
		mot.EMPREG = 'S'
) AS X LEFT JOIN 
(
	SELECT
		mot.CODMOT,
		mot.NOMMOT,
		mot.EMPREG,
		mtv.CODMTV,
		mtv.DESCRI,
		cam.CODCAM,
		cam.DATREF,
		cam.OBSERV
	FROM
		RODCAM_HIS cam LEFT JOIN RODMOT mot ON
			cam.CODMOT = mot.CODMOT
		LEFT JOIN RODMTV mtv ON
			cam.CODMTV = mtv.CODMTV
	WHERE
		mot.EMPREG = 'S'
) AS Y

ON X.CODCAM = Y.CODCAM