SELECT
	SUB1.DATA,
	SUM(SUB1.FATURAD0) AS FATURADO,
	SUM(SUB1.COMPRAS) AS COMPRAS,
	SUM(SUB1.FOLHA) AS FOLHA,
	SUM(SUB1.IMPOSTOS) AS IMPOSTOS--,
	--SUM(SUB1.OUTROS) AS OUTROS
FROM(
	SELECT
		CASE
			WHEN SUB.DATVEN >= GETDATE() THEN NULL
			ELSE SUBSTRING(CONVERT(VARCHAR(10),SUB.DATVEN + 1,103),4,7)
		END AS DATA,
		0.00 AS FATURAD0,
		CASE
			WHEN SUB.TIPDOC IN ('NPS','NF','NFS','NFE') THEN SUB.VALOR
			ELSE 0
		END AS COMPRAS,
		CASE
			WHEN SUB.TIPDOC IN ('ACT','ADS','CSP','CSF','DTS','FGT','PAR','REE','RES','SAL','SNR') THEN SUB.VALOR
			ELSE 0
		END AS FOLHA,
		CASE
			WHEN SUB.TIPDOC IN ('ICM','IST','RP2','IRF','ISS','ISF','OBA','PCS') THEN SUB.VALOR
			ELSE 0
		END AS IMPOSTOS--,
		--CASE
		--	WHEN SUB.TIPDOC IN ('ALT','ALP','COR','DIR','EMT','HON','SEG','TEL') THEN SUB.VALOR
		--	ELSE 0
		--END AS OUTROS
	FROM(
		SELECT
			PD.TIPDOC,
			(SELECT TOP 1 PDI.DATVEN
			 FROM PAGDOCI PDI
			 WHERE PDI.CODCLIFOR = PD.CODCLIFOR AND
				   PDI.SERIE = PD.SERIE AND
				   PDI.NUMDOC = PD.NUMDOC AND
				   DATVEN >= DATEADD(YEAR,-1,GETDATE())--SOMENTE RESULTADOS DOS ULTIMOS 12 MESES
			 ORDER BY DATVEN DESC
			)AS DATVEN,
			(SELECT TOP 1 PDI.VLRLIQ
			 FROM PAGDOCI PDI
			 WHERE PDI.CODCLIFOR = PD.CODCLIFOR AND
				   PDI.SERIE = PD.SERIE AND
				   PDI.NUMDOC = PD.NUMDOC AND
				   DATVEN >= DATEADD(YEAR,-1,GETDATE())--SOMENTE RESULTADOS DOS ULTIMOS 12 MESES
			 ORDER BY VLRLIQ DESC
			)AS VALOR
		FROM PAGDOC PD
	)AS SUB
	WHERE
		SUB.DATVEN IS NOT NULL
		
	UNION ALL

	SELECT
		SUBSTRING(CONVERT(VARCHAR(10),DATREC,103),4,7) AS DATA,
		VLRREC AS FATURADO,
		0.00 AS IMPOSTOS,
		0.00 AS COMPRAS,
		0.00 AS FOLHA--,
		--0.00 AS OUTROS
	FROM RECDOCI
	WHERE VLRREC > 0 AND DATREC >= DATEADD(YEAR,-1,GETDATE())--SOMENTE RESULTADOS DOS ULTIMOS 12 MESES
)AS SUB1
WHERE SUB1.DATA IS NOT NULL
GROUP BY SUB1.DATA
ORDER BY SUBSTRING(SUB1.DATA, 4, 4), SUB1.DATA