SELECT
	SUB.DATA,
	SUM(SUB.FATURADO) AS FATURADO,
	--SUM(SUB.GASTOS) AS GASTOS,
	SUM(SUB.GUARULHOS) AS GUARULHOS,
	SUM(SUB.CAMPINAS) AS CAMPINAS,
	SUM(SUB.CUBATAO) AS CUBATAO,
	SUM(SUB.DESPACHO) AS DESPACHO,
	SUM(SUB.TERMINAL) AS TERMINAL,
	SUM(SUB.CABOTAGEM) AS CABOTAGEM,
	SUM(SUB.SALTO) AS SALTO,
	SUM(SUB.RECIFE) AS RECIFE
FROM(
	SELECT
		CASE
			WHEN raz.DATREF >= GETDATE() THEN NULL
			ELSE SUBSTRING(CONVERT(VARCHAR(10),raz.DATREF,103),4,7)
		END AS DATA,
		CASE
			WHEN raz.DEBCRE = 'C' THEN rat.VALOR
			ELSE 0
		END AS FATURADO,
		CASE
			WHEN raz.DEBCRE = 'D' THEN rat.VALOR
			ELSE 0
		END AS GASTOS,
		CASE
			WHEN rat.CODUNN = 1 AND raz.DEBCRE = 'D' THEN rat.VALOR
			ELSE 0
		END AS GUARULHOS,
		CASE
			WHEN rat.CODUNN = 2 AND raz.DEBCRE = 'D' THEN rat.VALOR
			ELSE 0
		END AS CAMPINAS,
		CASE
			WHEN rat.CODUNN = 3 AND raz.DEBCRE = 'D' THEN rat.VALOR
			ELSE 0
		END AS CUBATAO,
		CASE
			WHEN rat.CODUNN = 4 AND raz.DEBCRE = 'D' THEN rat.VALOR
			ELSE 0
		END AS DESPACHO,
		CASE
			WHEN rat.CODUNN = 5 AND raz.DEBCRE = 'D' THEN rat.VALOR
			ELSE 0
		END AS TERMINAL,
		CASE
			WHEN rat.CODUNN = 6 AND raz.DEBCRE = 'D' THEN rat.VALOR
			ELSE 0
		END AS CABOTAGEM,
		CASE
			WHEN rat.CODUNN = 7 AND raz.DEBCRE = 'D' THEN rat.VALOR
			ELSE 0
		END AS SALTO,
		CASE
			WHEN rat.CODUNN = 8 AND raz.DEBCRE = 'D' THEN rat.VALOR
			ELSE 0
		END AS RECIFE
	FROM BANRAT rat
		 LEFT JOIN BANRAZ raz ON
				   --rat.ID_RAZ = raz.ID_RAZ
				   rat.NUMDOC = raz.NUMDOC AND
				   rat.CODFIL = raz.CODFIL AND
				   rat.TIPDOC = raz.TIPDOC AND
				   rat.CODCTA = raz.CODCTA
	WHERE raz.SITUAC NOT IN ('C','I') AND raz.DATREF >= DATEADD(SS, 1, DATEADD(MM, 1, DATEADD(MM, DATEDIFF(MM, 0, DATEADD(YEAR,-1,GETDATE())) - 1, 0))) 
) AS SUB
WHERE SUB.DATA IS NOT NULL
GROUP BY SUB.DATA
ORDER BY SUBSTRING(SUB.DATA, 4, 4), SUB.DATA

