SELECT act.CODNOT NF_ACT,
	   act.CODIGO ACT,
	   ost.CODNOT NF_OST,
	   ost.CODORD OST,
	   cte.CODNOT NF_CTRC,
	   cte.CODCON CTRC,
	   t.CODFEC
FROM TERCAL t
	 LEFT JOIN VW_RODCOL_RODICO act ON t.NUMDOC = act.CODIGO AND
									   t.SERDOC = act.SERCOL AND
									   t.FILDOC = act.CODFIL
	 LEFT JOIN VW_RODCOL_RODICO ost ON t.NUMDOC = ost.CODORD AND
									   t.SERDOC = ost.SERORD AND
									   t.FILDOC = ost.FILORD
	 LEFT JOIN VW_RODCOL_RODICO cte ON t.NUMDOC = cte.CODCON AND
									   t.SERDOC = cte.SERCON AND
									   t.FILDOC = cte.FILCON
WHERE (act.CODNOT IS NOT NULL OR ost.CODNOT IS NOT NULL OR cte.CODNOT IS NOT NULL) AND
	   t.DEBCRE = 'C' AND
	   t.CODFEC IS NOT NULL
ORDER BY t.CODFEC