SELECT  R.CODREL,
		R.DESCRI,
		R.RPT,
		R.USUINC,
		R.DATINC,
		R.USUATU,
		R.DATATU,
		RM.DESCRI AS MODULO ,  
		RSM.DESCRI AS SUBMODULO 
FROM RELATO R,
	 RELNIV RN,
	 RELMOD RM,
	 RELSMO RSM
WHERE R.CODNIV = RN.CODNIV  AND
	  R.CODSMO = RSM.CODSMO  AND
	  RSM.CODMOD = RM.CODMOD  AND
	  ISNULL(INATIV, 'N') <> 'S' --AND
	  --((R.USUINC = 'ANTONIO.NETO') OR (R.USUATU = 'ANTONIO.NETO'))