SELECT  dup.NUMDUP AS FATURA,
		con.TOTFRE AS TOTFRETE,
		dup.VLRDUP AS TOTFATURA,
		con.CODCON AS CTE,
		dup.OBSERV AS OBS,
		ipr.ORDCOM,
		con.DATEMI
FROM RODCON con
	 LEFT JOIN RODDUP dup ON
			   con.NUMDUP = dup.NUMDUP AND
			   con.FILDUP = dup.CODFIL
	 LEFT JOIN VW_IND_FAT vif ON
			   con.CODCON = vif.CODCON AND
			   con.SERCON = vif.SERCON AND
			   con.CODFIL = vif.FILCON
	 LEFT JOIN RODIPR ipr ON
			   vif.NUM_PROG_CARGA = ipr.CODIGO AND
			   vif.FILIAL_PROG_CARGA = ipr.CODFIL
WHERE con.CODCON IN (34087,34091,34214)
