SELECT
	cpl.CODFIL,
	cpl.SERCON,
	cpl.CODCON,
	cpl.FILCPL,
	cpl.SERCPL,
	cpl.CODCPL,
	(SELECT TOP 1 con2.TIPCON
	 FROM RODCON con2
	 WHERE con2.CODCON = cpl.CODCON AND
		   con2.SERCON = cpl.SERCON AND
		   con2.CODFIL = cpl.CODFIL) AS TIPCON
FROM RODCON con
	 INNER JOIN RODCPL cpl ON
				con.CODCON = cpl.CODCPL AND
				con.SERCON = cpl.SERCPL AND
				con.CODFIL = cpl.FILCPL

UNION ALL

SELECT
	r.CODFIL,
	r.SERCON,
	r.CODCON,
	cal.FILDOC AS FILCPL,
	cal.SERDOC AS SERCPL,
	cal.NUMDOC AS CODCPL,
	r.TIPCON AS TIPCON
FROM RODCON r
	 LEFT JOIN ESTFEC fec ON
				r.CODCON = fec.NUMDOC AND
				r.SERCON = fec.SERDOC AND
				r.CODFIL = fec.FILDOC
	 LEFT JOIN ESTCAL cal ON
				fec.CODFEC = cal.CODFEC
WHERE r.TIPCON = 'E' AND
	  r.SITUAC <> 'C' AND
	  r.CODCON <> 32275