------------------------------------TIPCON---------------------------------------
SELECT CODCON,TIPCON,TIPDOC,DATEMI FROM RODCON WHERE TIPCON = 'C' --COMPLEMENTO
SELECT CODCON,TIPCON,TIPDOC,DATEMI FROM RODCON WHERE TIPCON = 'E' --ESTADIA
SELECT CODCON,TIPCON,TIPDOC,DATEMI FROM RODCON WHERE TIPCON = 'N' --NORMAL
SELECT CODCON,TIPCON,TIPDOC,DATEMI FROM RODCON WHERE TIPCON = 'A' --TRANSF. ACT
SELECT CODCON,TIPCON,TIPDOC,DATEMI FROM RODCON WHERE TIPCON = 'B' --SUBSTITUTO
SELECT CODCON,TIPCON,TIPDOC,DATEMI FROM RODCON WHERE TIPCON = 'H' --REDESPACHO
SELECT CODCON,TIPCON,TIPDOC,DATEMI FROM RODCON WHERE TIPCON = 'M' --MULTIMODAL
SELECT CODCON,TIPCON,TIPDOC,DATEMI FROM RODCON WHERE TIPCON = 'R' --REENTREGA
SELECT CODCON,TIPCON,TIPDOC,DATEMI FROM RODCON WHERE TIPCON = 'S' --OPERAÇÃO SEM NF
SELECT CODCON,TIPCON,TIPDOC,DATEMI FROM RODCON WHERE TIPCON = 'U' --SUBCONTRATAÇÃO

------------------------------------SITUAC---------------------------------------
SELECT * FROM RODCON WHERE SITUAC = 'B' --BAIXADO
SELECT * FROM RODCON WHERE SITUAC = 'C' --CANCELADO
SELECT * FROM RODCON WHERE SITUAC = 'D' --CADASTRADO
SELECT * FROM RODCON WHERE SITUAC = 'E' --EMITIDO
SELECT * FROM RODCON WHERE SITUAC = 'I' --INCONSISTENTE