SELECT * FROM RODPOR --CADASTRO DE PORTARIAS
SELECT * FROM PORVIS --CADASTRO DE VISITANTES
SELECT * FROM POREMP --CADASTRO DE EMPRESAS VISITANTES
SELECT * FROM RODMPO --MOVIMENTAÇÃO VEÍCULO
SELECT * FROM RODMRE --MOVIMENTO RECEPÇÃO